version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: estech_postgres
    environment:
      POSTGRES_DB: estechdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  backend:
    build: ./estechbackend
    container_name: estech_backend
    env_file:
      - ./estechbackend/.env
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - webnet

  frontend:
    build: ./estechfrontend
    container_name: estech_frontend
    ports:
      - "80:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - certs:/etc/ssl/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

volumes:
  static_volume:
  postgres_data:
  certs:

networks:
  webnet:
