# Generated by Django 5.0.4 on 2024-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_characteristics',
            field=models.TextField(blank=True),
        ),
    ]
