# Generated by Django 5.0.4 on 2024-07-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
