# Generated by Django 5.0.4 on 2024-08-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
