# Generated by Django 5.0.4 on 2024-08-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
