# Generated by Django 5.0.4 on 2024-05-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sameTypeProduct',
            new_name='same_type_product',
        ),
    ]
