# Generated by Django 5.0.4 on 2024-05-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productreviewcomment',
            name='parent',
        ),
    ]
