# Generated by Django 5.0.4 on 2024-05-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_productreview_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='productreviewcomment',
            old_name='user',
            new_name='author',
        ),
    ]
