# Generated by Django 5.0.4 on 2024-05-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_productcomment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'Комментарие товаров', 'verbose_name_plural': 'Комментарии товаров'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-rating'], 'verbose_name': 'Отзыв товаров', 'verbose_name_plural': 'Отзывы товаров'},
        ),
        migrations.AlterModelOptions(
            name='productreviewcomment',
            options={'verbose_name': 'Ответ на отзывы', 'verbose_name_plural': 'Ответы на отзывы'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name': 'Комментарие пользователей', 'verbose_name_plural': 'Комментарии пользователей'},
        ),
    ]
